home:
    path: /
    controller: App\Controller\HomeController::index

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout


#index:
#    path: /
#    controller: App\Controller\HomeController::index

# config/routes.yaml



